/**
 * Canonical specialization list — kept identical (by design, not by shared import — Dart and TS
 * can't share a source file directly) in mobile/lib/utils/specializations.dart. If you add one
 * here, add it there too, and vice versa.
 */
export const SPECIALIZATIONS = [
  'General Physician',
  'Family Medicine',
  'Pediatrician',
  'Gynecologist / Obstetrician',
  'Cardiologist',
  'Dermatologist',
  'Dentist',
  'ENT Specialist',
  'Orthopedist',
  'Neurologist',
  'Psychiatrist',
  'Psychologist / Counselor',
  'Ophthalmologist',
  'Endocrinologist',
  'Gastroenterologist',
  'Pulmonologist',
  'Nephrologist',
  'Urologist',
  'Oncologist',
  'Rheumatologist',
  'Allergist / Immunologist',
  'General Surgeon',
  'Plastic Surgeon',
  'Dietitian / Nutritionist',
  'Physiotherapist',
  'Diabetologist',
  'Hematologist',
  'Infectious Disease Specialist',
  'Geriatrician',
  'Sexologist / Andrologist',
  'Ayurveda Practitioner',
  'Homeopath',
  'Sports Medicine Specialist',
  'Pain Management Specialist',
  'Radiologist',
  'Anesthesiologist',
  'Podiatrist',
] as const;
