/// Canonical specialization list — kept identical (by design, not shared code — Dart and the
/// server's TypeScript can't share a source file) in server/src/specializations.ts. Add a new
/// one to both if you add one here.
const kSpecializations = [
  'General Physician',
  'Family Medicine',
  'Pediatrician',
  'Gynecologist / Obstetrician',
  'Cardiologist',
  'Dermatologist',
  'Dentist',
  'ENT Specialist',
  'Orthopedist',
  'Neurologist',
  'Psychiatrist',
  'Psychologist / Counselor',
  'Ophthalmologist',
  'Endocrinologist',
  'Gastroenterologist',
  'Pulmonologist',
  'Nephrologist',
  'Urologist',
  'Oncologist',
  'Rheumatologist',
  'Allergist / Immunologist',
  'General Surgeon',
  'Plastic Surgeon',
  'Dietitian / Nutritionist',
  'Physiotherapist',
  'Diabetologist',
  'Hematologist',
  'Infectious Disease Specialist',
  'Geriatrician',
  'Sexologist / Andrologist',
  'Ayurveda Practitioner',
  'Homeopath',
  'Sports Medicine Specialist',
  'Pain Management Specialist',
  'Radiologist',
  'Anesthesiologist',
  'Podiatrist',
];
